### ISSUE TITLE
Control replay concurrency

### ISSUE THREAD

**Issue by yhahn** [mapbox/cloudfront-log-reader#13]
There's a variety of factors/ways we might do this:

- Using object high watermark on the replay stream (https://github.com/mapbox/cloudfront-log-reader/blob/master/index.js#L85)
- Controlling concurrency of request queue (https://github.com/mapbox/cloudfront-log-reader/blob/master/index.js#L89)
- Other?

cc @emilymcafee 

Also @rclark who has way more experience with this than I do.

**Comment by rclark** [comment]
Maybe you have the transform stream accept a highwatermark:

```js
function RequestStream(options) {
  var hwm = options.highWaterMark || someDefaultMaxConcurrency;
```

Then use that as the request queue concurrency:

```js
requestStream.queue = queue(hwm);
```

Then also use that `hwm` in the determination of whether or not it is acceptable for the `_transform` function to "consume" the passed in chunk. 

```js
if (requestStream.pending > 1.5 * hwm)
  return setImmediate(requestStream._transform.bind(requestStream), pathname, enc, callback);
```

Then your stream will backpressure based on the provided highWaterMark and won't make requests at infinite concurrency.
