### ISSUE TITLE
rename + split up

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/cloudfront-log-reader#24]
#### log reading

Soon this project will support reading ELB logs (it already does, to some extent.) Let's rename - it's still getting everything from S3 and expecting AWS logs, so we could do something like `aws-log-reader`. We also have https://github.com/mapbox/log-reader (cc @tmcw) - I wonder if we should take over this namespace or combine these projects.

#### preparing

A bunch of these streams do some kind of preparation - extract paths, filter by regex, sample, etc - I'm ok with keeping preparation/transforming under the name "reader," unless there are objections.

#### replaying

Right now we also provide a stream for replaying logs against a given host, which doesn't make sense at all with the name "cloudfront-log-reader." Let's move this into a new repo and expand its functionality. "log-replayer" could go nicely with "log-reader"..... or "log-replay" / "log-read"??? `D:` 

Thoughts, anyone? @yhahn @ianshward @willwhite

**Comment by yhahn** [comment]
Hmm, so one thing that I never circled back to refactoring out was updating s3scan to make use of the new gzip scan functionality (https://github.com/mapbox/s3scan/pull/14#issue-140786857).

This would essentially melt away the log reading part of cf-log-reader I believe leaving just the prep / replay part.

`log-replay` makes sense to me -- I wonder if ^^ changes the naming convention of the tool for doing prep though if "reading" can now be handled 100% by s3scan?
