### ISSUE TITLE
Support ELB2 logs 

### ISSUE THREAD

**Issue by yhahn** [mapbox/cloudfront-log-reader#30]
The ELB2 log format is slightly different from ELB1 (http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html).

Should be reasonably easy to autodetect and adjust based on the number of columns.

cc @aarthykc @emilymcafee

**Comment by emilymcafee** [comment]
Done in https://github.com/mapbox/cloudfront-log-reader/pull/31.
